name: "deploy TYPO3 extension"
description: "deploys TYPO3 extension via scp (appleboy/scp-action)"

inputs:
  host:
    description: "the host domain to deploy the extension"
    required: true
  target_path:
    description: "the path on the host to deploy the extension [TYPO3]/ext/[extension_key]"
    required: true
  user_name: 
    description: "name of the user to use at the login"
    required: true
  user_password:
    description: "password of the user to use at the login"
    required: true

runs:
  using: "composite"
  steps:

  - name: install bash
    uses: actions/checkout@v3

  - name: make it runable
    working-directory: ./
    run: echo "Hello, World!"
