name: "deploy TYPO3 extension"
description: "deploys TYPO3 extension via scp (appleboy/scp-action)"

inputs:
  host:
    description: "the host domain to deploy the extension"
    required: true
  target_path:
    description: "the path on the host to deploy the extension [TYPO3]/ext/[extension_key]"
    required: true
  user_name: 
    description: "name of the user to use at the login"
    required: true
  user_password:
    description: "password of the user to use at the login"
    required: true

runs:
  using: "composite"
  steps:

  - name: 'Checkout: actions'
    uses: actions/checkout@v3

  - name: 'Checkout: local'
    uses: actions/checkout@v3
    with:
      repository: peni4142/typo3-scp-deployment
      path: 'typo3-scp-deployment-template'
      ref: 'main'

  - name: create deployment
    shell: bash
    run: node ./typo3-scp-deployment-template/complex-copy.js

  - name: copy extension to production server
    uses:  appleboy/scp-action@master
    with:
      host: ${{ inputs.host }}
      username: ${{ inputs.user_name }}
      password: ${{ inputs.user_password }}
      port: 22
      source: "deployment/*"
      target: ${{ inputs.target_path }}
      strip_components: 1
      overwrite: true
